// customer-portal/src/components/ProfileModal/ProfileModal.tsx
import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { useAuth } from '../../context/AuthContext'
import { supabase } from '../../services/supabase'
import toast from 'react-hot-toast'
import { X } from 'lucide-react'

interface ProfileModalProps {
  isOpen: boolean
  onClose: () => void
}

export function ProfileModal({ isOpen, onClose }: ProfileModalProps) {
  const { user, role } = useAuth()
  const [fullName, setFullName] = useState(user?.user_metadata?.full_name || '')
  const [newPassword, setNewPassword] = useState('')
  const [saving, setSaving] = useState(false)

  const handleUpdateProfile = async (e: React.FormEvent) => {
    e.preventDefault()
    setSaving(true)
    try {
      const updates: { data?: { full_name: string }; password?: string } = {}
      if (fullName.trim()) {
        updates.data = { full_name: fullName.trim() }
        await supabase.from('profiles').update({ full_name: fullName.trim() }).eq('id', user?.id)
      }
      if (newPassword.trim()) {
        if (newPassword.trim().length < 6) {
          throw new Error('Password must be at least 6 characters')
        }
        updates.password = newPassword.trim()
      }

      const { error } = await supabase.auth.updateUser(updates)
      if (error) throw error

      toast.success('Profile updated successfully!')
      setNewPassword('')
      onClose()
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : 'Failed to update profile'
      toast.error(msg)
    } finally {
      setSaving(false)
    }
  }

  if (!isOpen) return null

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-md">
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 10 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 10 }}
          className="w-full max-w-md p-6 sm:p-8 rounded-3xl glass-panel shadow-glow border border-indigo-500/20"
        >
          <div className="flex items-center justify-between mb-6 pb-3 border-b border-slate-800">
            <div>
              <h2 className="text-xl font-bold text-white tracking-tight">Account & Profile Settings</h2>
              <p className="text-xs text-slate-400 mt-0.5">Manage your personal information and password</p>
            </div>
            <button onClick={onClose} className="text-slate-400 hover:text-white p-1 rounded-lg hover:bg-slate-800 transition-colors">
              <X className="w-5 h-5" />
            </button>
          </div>

          <form onSubmit={handleUpdateProfile} className="space-y-4">
            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-slate-400 mb-1">Email (Read Only)</label>
              <input type="text" disabled value={user?.email || ''} className="w-full px-3.5 py-2.5 rounded-xl bg-slate-950 border border-slate-800 text-slate-400 text-sm cursor-not-allowed" />
            </div>

            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-slate-400 mb-1">Display Name</label>
              <input 
                type="text" 
                value={fullName} 
                onChange={(e) => setFullName(e.target.value)}
                placeholder="John Doe" 
                className="w-full px-3.5 py-2.5 rounded-xl bg-slate-900/90 border border-slate-800 text-white text-sm focus:outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/20" 
              />
            </div>

            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-slate-400 mb-1">Change Password (Optional)</label>
              <input 
                type="password" 
                value={newPassword}
                onChange={(e) => setNewPassword(e.target.value)}
                placeholder="Leave blank to keep current password" 
                className="w-full px-3.5 py-2.5 rounded-xl bg-slate-900/90 border border-slate-800 text-white text-sm focus:outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/20" 
              />
            </div>

            <div className="p-3 rounded-xl bg-slate-900/60 border border-white/5 flex items-center justify-between text-xs text-slate-400">
              <span>Account Role:</span>
              <span className="font-semibold capitalize text-indigo-400">{role || 'Customer'}</span>
            </div>

            <div className="flex items-center justify-end gap-3 pt-4 border-t border-slate-800">
              <button type="button" onClick={onClose} className="px-4 py-2 rounded-xl text-slate-400 hover:text-white hover:bg-slate-800 text-xs font-medium transition-colors">Cancel</button>
              <button type="submit" disabled={saving} className="px-5 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-medium transition-all shadow-md shadow-indigo-600/20 disabled:opacity-50">
                {saving ? 'Saving...' : 'Save Changes'}
              </button>
            </div>
          </form>
        </motion.div>
      </div>
    </AnimatePresence>
  )
}

// support-workspace/src/app/components/profile-modal/profile-modal.component.ts
import { Component, input, output, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { LucideAngularModule } from 'lucide-angular';
import { Profile } from '../../core/services/supabase.service';

@Component({
  selector: 'app-profile-modal',
  standalone: true,
  imports: [CommonModule, FormsModule, LucideAngularModule],
  templateUrl: './profile-modal.component.html'
})
export class ProfileModalComponent {
  isOpen = input<boolean>(false);
  profile = input<Profile | null>(null);
  close = output<void>();
  save = output<{ fullName: string; password?: string }>();

  fullName = '';
  newPassword = '';
  saving = signal(false);

  ngOnInit() {
    if (this.profile()?.full_name) {
      this.fullName = this.profile()!.full_name;
    }
  }

  handleSave() {
    this.save.emit({
      fullName: this.fullName.trim(),
      password: this.newPassword.trim() || undefined
    });
  }
}

@if (isOpen()) {
  <div class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-md">
    <div class="w-full max-w-md p-6 sm:p-8 rounded-3xl glass-panel shadow-glow border border-emerald-500/20 animate-in fade-in zoom-in duration-200">
      <div class="flex items-center justify-between mb-6 pb-3 border-b border-slate-800">
        <div>
          <h2 class="text-xl font-bold text-white tracking-tight">Staff Account Settings</h2>
          <p class="text-xs text-slate-400 mt-0.5">Manage your operator name and security</p>
        </div>
        <button (click)="close.emit()" class="text-slate-400 hover:text-white p-1 rounded-lg hover:bg-slate-800 transition-colors">
          <lucide-icon [name]="'x'" class="w-5 h-5"></lucide-icon>
        </button>
      </div>

      <form (ngSubmit)="handleSave()" class="space-y-4">
        <div>
          <label class="block text-xs font-semibold uppercase tracking-wider text-slate-400 mb-1">Display Name</label>
          <input 
            type="text" 
            [(ngModel)]="fullName" 
            name="fullName"
            placeholder="Agent Smith" 
            class="w-full px-3.5 py-2.5 rounded-xl bg-slate-900/90 border border-slate-800 text-white text-sm focus:outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/20" 
          />
        </div>

        <div>
          <label class="block text-xs font-semibold uppercase tracking-wider text-slate-400 mb-1">New Password (Optional)</label>
          <input 
            type="password" 
            [(ngModel)]="newPassword" 
            name="newPassword"
            placeholder="Leave blank to keep unchanged" 
            class="w-full px-3.5 py-2.5 rounded-xl bg-slate-900/90 border border-slate-800 text-white text-sm focus:outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/20" 
          />
        </div>

        @if (profile(); as p) {
          <div class="p-3 rounded-xl bg-slate-900/60 border border-white/5 flex items-center justify-between text-xs text-slate-400">
            <span>Assigned Role:</span>
            <span class="font-semibold capitalize text-emerald-400">{{ p.role }}</span>
          </div>
        }

        <div class="flex items-center justify-end gap-3 pt-4 border-t border-slate-800">
          <button type="button" (click)="close.emit()" class="px-4 py-2 rounded-xl text-slate-400 hover:text-white hover:bg-slate-800 text-xs font-medium transition-colors">Cancel</button>
          <button type="submit" [disabled]="saving()" class="px-5 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-medium transition-all shadow-md shadow-emerald-600/20 disabled:opacity-50">
            {{ saving() ? 'Saving...' : 'Update Settings' }}
          </button>
        </div>
      </form>
    </div>
  </div>
}
