// support-workspace/src/app/components/settings-view/settings-view.component.ts
import { Component, input, output, effect, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Profile } from '../../core/services/supabase.service';
import { ToastService } from '../../core/services/toast.service';

@Component({
  selector: 'app-settings-view',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './settings-view.component.html'
})
export class SettingsViewComponent {
  private toast = inject(ToastService);

  profile = input<Profile | null>(null);
  save = output<{ fullName: string; password?: string }>();

  name = '';
  password = '';
  confirmPassword = '';

  constructor() {
    effect(() => {
      const p = this.profile();
      if (p) this.name = p.full_name;
    });
  }

  private validatePassword(pwd: string): string | null {
    if (pwd.length < 8) return 'Password must be at least 8 characters long';
    if (!/[A-Z]/.test(pwd)) return 'Password must contain at least one uppercase letter (A-Z)';
    if (!/[a-z]/.test(pwd)) return 'Password must contain at least one lowercase letter (a-z)';
    if (!/[0-9]/.test(pwd)) return 'Password must contain at least one number (0-9)';
    if (!/[^A-Za-z0-9]/.test(pwd)) return 'Password must contain at least one special character (!@#$%^&*)';
    return null;
  }

  handleSave() {
    const trimmedName = this.name.trim();
    if (!trimmedName || trimmedName.length < 2) {
      this.toast.error('Full name must be at least 2 characters');
      return;
    }

    const trimmedPass = this.password.trim();
    if (trimmedPass) {
      const err = this.validatePassword(trimmedPass);
      if (err) {
        this.toast.error(err);
        return;
      }
      if (trimmedPass !== this.confirmPassword.trim()) {
        this.toast.error('Passwords do not match');
        return;
      }
    }

    this.save.emit({
      fullName: trimmedName,
      password: trimmedPass || undefined
    });
    this.password = '';
    this.confirmPassword = '';
  }
}

<div class="rounded-3xl glass-panel p-6 sm:p-8 border border-white/5 max-w-2xl">
  <h2 class="text-xl font-bold text-white mb-1">Staff Account Settings</h2>
  <p class="text-xs text-slate-400 mb-6">Manage your staff credentials, display name, and security preferences.</p>

  <form (ngSubmit)="handleSave()" class="space-y-5">
    <div>
      <label class="block text-xs font-semibold uppercase tracking-wider text-slate-400 mb-1.5">Full Name</label>
      <input
        type="text"
        [(ngModel)]="name"
        name="name"
        class="w-full px-4 py-2.5 rounded-xl bg-slate-900/80 border border-slate-800 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-emerald-500"
      />
    </div>

    <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
      <div>
        <label class="block text-xs font-semibold uppercase tracking-wider text-slate-400 mb-1.5">New Password</label>
        <input
          type="password"
          [(ngModel)]="password"
          name="password"
          placeholder="Leave blank to keep current"
          class="w-full px-4 py-2.5 rounded-xl bg-slate-900/80 border border-slate-800 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-emerald-500"
        />
      </div>

      <div>
        <label class="block text-xs font-semibold uppercase tracking-wider text-slate-400 mb-1.5">Confirm Password</label>
        <input
          type="password"
          [(ngModel)]="confirmPassword"
          name="confirmPassword"
          placeholder="Re-enter password"
          class="w-full px-4 py-2.5 rounded-xl bg-slate-900/80 border border-slate-800 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-emerald-500"
        />
      </div>
    </div>

    @if (password) {
      <div class="p-3.5 rounded-2xl bg-slate-900/90 border border-white/5 text-[11px] text-slate-400">
        <span class="font-semibold text-slate-300 block mb-1">Password Complexity Rules:</span>
        <p>Must be at least 8 characters with 1 uppercase, 1 lowercase, 1 number, and 1 special symbol (!&#64;#$).</p>
      </div>
    }

    <div class="p-4 rounded-2xl bg-slate-900/60 border border-white/5 text-xs text-slate-400">
      <span class="font-semibold text-white block mb-1">Assigned Role & Permissions:</span>
      <span class="px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
        {{ profile()?.role === 'manager' ? 'Operations Manager (Full Administrative Access)' : 'Support Agent (Queue Triage & Resolution)' }}
      </span>
    </div>

    <button
      type="submit"
      class="px-5 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-semibold shadow-md shadow-emerald-600/20 transition-all"
    >
      Save Changes
    </button>
  </form>
</div>

// customer-portal/src/components/Settings/SettingsView.tsx
import { useState, useEffect } from 'react'
import { User, Lock, CheckCircle2 } from 'lucide-react'
import { useAuth } from '@/context/AuthContext'
import { authApi } from '@/api'
import { notify } from '@/lib/toast'

export function SettingsView() {
  const { profile, user } = useAuth()
  const [fullName, setFullName] = useState('')
  const [password, setPassword] = useState('')
  const [confirmPassword, setConfirmPassword] = useState('')
  const [saving, setSaving] = useState(false)

  useEffect(() => {
    if (profile) setFullName(profile.full_name || '')
  }, [profile])

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault()
    const trimmedName = fullName.trim()
    if (!trimmedName || trimmedName.length < 2) {
      notify.error('Full name must be at least 2 characters')
      return
    }

    if (password) {
      if (password.length < 8 || !/[A-Z]/.test(password) || !/[0-9]/.test(password) || !/[^A-Za-z0-9]/.test(password)) {
        notify.error('Password must be 8+ chars with uppercase, number, and special character')
        return
      }
      if (password !== confirmPassword) {
        notify.error('Passwords do not match')
        return
      }
    }

    setSaving(true)
    try {
      if (trimmedName) await authApi.updateProfile(trimmedName)
      if (password) await authApi.updatePassword(password)
      notify.success('Account preferences saved successfully!')
      setPassword('')
      setConfirmPassword('')
    } catch (err: unknown) {
      notify.error(err instanceof Error ? err.message : 'Failed to update preferences')
    } finally {
      setSaving(false)
    }
  }

  return (
    <div className="rounded-3xl glass-panel p-6 sm:p-8 border border-white/5 max-w-2xl">
      <div className="flex items-center gap-3 mb-6 pb-4 border-b border-slate-800">
        <div className="p-2.5 rounded-2xl bg-indigo-500/10 text-indigo-400 border border-indigo-500/20">
          <User className="w-5 h-5" />
        </div>
        <div>
          <h3 className="text-base font-bold text-white">Account & Security Preferences</h3>
          <p className="text-xs text-slate-400">Update your profile display name and secure your login password</p>
        </div>
      </div>

      <form onSubmit={handleSave} className="space-y-5">
        <div>
          <label className="block text-xs font-semibold uppercase tracking-wider text-slate-400 mb-1.5">Email Address (Read-Only)</label>
          <input type="text" disabled value={user?.email || ''} className="w-full px-4 py-2.5 rounded-xl bg-slate-950/80 border border-slate-800 text-xs text-slate-400 cursor-not-allowed font-mono" />
        </div>

        <div>
          <label className="block text-xs font-semibold uppercase tracking-wider text-slate-400 mb-1.5">Full Name *</label>
          <input type="text" value={fullName} onChange={(e) => setFullName(e.target.value)} placeholder="John Doe" className="w-full px-4 py-2.5 rounded-xl bg-slate-900/90 border border-slate-800 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/20" />
        </div>

        <div className="pt-3 border-t border-slate-800/80">
          <h4 className="text-xs font-semibold text-slate-300 mb-3 flex items-center gap-1.5">
            <Lock className="w-3.5 h-3.5 text-indigo-400" />
            <span>Change Account Password (Optional)</span>
          </h4>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-slate-400 mb-1.5">New Password</label>
              <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Leave blank to keep current" className="w-full px-4 py-2.5 rounded-xl bg-slate-900/90 border border-slate-800 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/20" />
            </div>
            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-slate-400 mb-1.5">Confirm New Password</label>
              <input type="password" value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} placeholder="Re-enter new password" className="w-full px-4 py-2.5 rounded-xl bg-slate-900/90 border border-slate-800 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/20" />
            </div>
          </div>

          {password && (
            <div className="mt-3 p-3.5 rounded-2xl bg-slate-900/90 border border-white/5 text-xs space-y-1 text-slate-400">
              <span className="font-semibold text-slate-300 block mb-1 text-[11px]">Password Complexity:</span>
              <div className={`flex items-center gap-1.5 text-[11px] ${password.length >= 8 ? 'text-emerald-400' : 'text-slate-400'}`}><CheckCircle2 className="w-3 h-3 flex-shrink-0" /><span>8+ characters</span></div>
              <div className={`flex items-center gap-1.5 text-[11px] ${/[A-Z]/.test(password) ? 'text-emerald-400' : 'text-slate-400'}`}><CheckCircle2 className="w-3 h-3 flex-shrink-0" /><span>1 uppercase (A-Z)</span></div>
              <div className={`flex items-center gap-1.5 text-[11px] ${/[0-9]/.test(password) ? 'text-emerald-400' : 'text-slate-400'}`}><CheckCircle2 className="w-3 h-3 flex-shrink-0" /><span>1 number (0-9)</span></div>
              <div className={`flex items-center gap-1.5 text-[11px] ${/[^A-Za-z0-9]/.test(password) ? 'text-emerald-400' : 'text-slate-400'}`}><CheckCircle2 className="w-3 h-3 flex-shrink-0" /><span>1 special symbol (!@#$)</span></div>
            </div>
          )}
        </div>

        <button type="submit" disabled={saving} className="px-6 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold shadow-md shadow-indigo-600/30 disabled:opacity-50 transition-all">
          {saving ? 'Saving Preferences...' : 'Save Account Settings'}
        </button>
      </form>
    </div>
  )
}
